spring:
  profiles:
    active:
    - dev
    
---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: mySpringCloud-config-dept-client-8001
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud01?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
mybatis:
  mapper-locations:
  - classpath:mapper/*.xml
  type-aliases-package: classpath*:com.test.entity
eureka:
  client:
    register-with-eureka: false #当前eureka-server自己不注册进服务列表中
    fetch-registry: false  #不通过eureka获取注册信息
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
---
spring:
  profiles: test #测试环境
  application:
    name: mySpringCloud-config-dept-client-8001
  datasource: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud02?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
mybatis:
  mapper-locations:
  - classpath:mapper/*.xml
  type-aliases-package: classpath*:com.test.entity
eureka:
  client:
    register-with-eureka: false #当前eureka-server自己不注册进服务列表中
    fetch-registry: false  #不通过eureka获取注册信息
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/