spring:
  profiles:
    active:
    - dev
    
---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud03?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
mybatis:
  mapper-locations:
  - classpath:mapper/*.xml
  type-aliases-package: classpath*:com.test.entity
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
---
server:
  port: 8001
spring:
  profiles: test #测试环境
  application:
    name: microservicecloud-config-dept-client
  datasource: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud02?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
mybatis:
  mapper-locations:
  - classpath:mapper/*.xml
  type-aliases-package: classpath*:com.test.entity
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/